# Generated by Django 4.1 on 2022-10-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.champion')),
                ('initial_heal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heal', to='items.item')),
                ('initial_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='items.item')),
            ],
        ),
    ]
