# Generated by Django 4.1 on 2022-10-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_build'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Build',
        ),
    ]
