# Generated by Django 4.1 on 2022-10-23 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_delete_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.champion')),
                ('fifth_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth', to='items.item')),
                ('first_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='items.item')),
                ('fourth_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='items.item')),
                ('initial_heal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heal', to='items.item')),
                ('initial_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='items.item')),
                ('initial_ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='items.item')),
                ('second_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='items.item')),
                ('sixth_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth', to='items.item')),
                ('third_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
